platform :ios, '14.0'

plugin 'cocoapods-deintegrate', :version => '1.0.5'
plugin 'cocoapods-generate', :version => '0.3.2'


load File.join(ENV['FLUTTER_ROOT'] || File.expand_path(File.join('..', '..', 'flutter')), 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end